sochina:
  xss-properties:
    sensitiveData: <,>,&,(,),(,),\,@,;,=,^
    pattern:
      script: <\\s*script\\b[^>]*>(.*?)<\\s*/\\s*script\\s*>
      onload: (<[^>]*)onload=([^>]*>)
      onclick: (<[^>]*)onclick=([^>]*>)
      ondbclick: (<[^>]*)ondbclick=([^>]*>)
      onchange: (<[^>]*)onchange=([^>]*>)
      onblur: (<[^>]*)onblur=([^>]*>)
      onfocus: (<[^>]*)onfocus=([^>]*>)
      onkeypress: (<[^>]*)onkeypress=([^>]*>)
      onkeydown: (<[^>]*)onkeydown=([^>]*>)
      onkeyup: (<[^>]*)onkeyup=([^>]*>)
      onmousedown: (<[^>]*)onmousedown=([^>]*>)
      onmousemove: (<[^>]*)onmousemove=([^>]*>)
      onmouseout: (<[^>]*)onmouseout=([^>]*>)