spring:
  redis:
    host: 127.0.0.1
    port: 51055
    database: 0
    password: ENC(926a0936d2d30c9a26af58ad01df435e593a5bfc6956b69fb39f4e3f0f64cf32)
#  main:
#    lazy-initialization: true
jasypt:
  encryptor:
    bean: SM4EncryptorByEcb
sochina:
  single:
    enable: false
  security:
    url-list:
      # - /swagger-resources/**
      - /v2/api-docs**
      - /webjars/**
      - /**/swagger-ui.html**
      # - /nacos-consumer/**
  tomcat-properties:
    enable: true
    userConstraint: CONFIDENTIAL
    pattern: /*
    omittedMethod:
      - GET
      - POST
    useHttpOnly: true
    allowTrace: true
    cookieSameSite: LAX
  spring-session-properties:
    enable: true
    cookieName: JSESSIONID
    domainName: localhost
    cookiePath: /
    coolieMaxAge: 3600
    sameSite: Lax
    useHttpOnlyCookie: true
    # 如果浏览器阻拦set-cookie，这里设置true
    useSecureCookie: false
  sql-properties:
    enable: true
    pattern: ((\\%3D)|(=))[^\n]*((\\%27)|(')|(--)|(\\%3B)|(;))
    sensitive-data: DELETE,UPDATE,INSERT,TRUNCATE,DROP,ALTER
    keyword: SELECT,FROM,WHERE,AND,OR,ORDER,BY,GROUP,HAVING,UNION,ALL
    exclude-url:
      - /demo/demo
  xss-properties:
    enable: true
    sensitive-data: <,>,&,(,),(,),\,@,;,=,^
    pattern:
      script: <\\s*script\\b[^>]*>(.*?)<\\s*/\\s*script\\s*>
      onload: (<[^>]*)onload=([^>]*>)
      onclick: (<[^>]*)onclick=([^>]*>)
      ondbclick: (<[^>]*)ondbclick=([^>]*>)
      onchange: (<[^>]*)onchange=([^>]*>)
      onblur: (<[^>]*)onblur=([^>]*>)
      onfocus: (<[^>]*)onfocus=([^>]*>)
      onkeypress: (<[^>]*)onkeypress=([^>]*>)
      onkeydown: (<[^>]*)onkeydown=([^>]*>)
      onkeyup: (<[^>]*)onkeyup=([^>]*>)
      onmousedown: (<[^>]*)onmousedown=([^>]*>)
      onmousemove: (<[^>]*)onmousemove=([^>]*>)
      onmouseout: (<[^>]*)onmouseout=([^>]*>)
    exclude-url:
      - /demo/demo
  response-properties:
    enable: true
    order: 0
    header:
      Content-Security-Policy: default-src 'self'; script-src 'self'; frame-ancestors 'self'; object-src 'none'
      X-Content-Type-Options: nosniff
      X-XSS-Protection: 1; mode=block
      Referer-Policy: origin
  cors-properties:
    enable: true
    order: -1
    all-allowed: true
    allowed-header: x-requested-with,authorization,Content-Type,Authorization,credential,X-XSRF-TOKEN,token,username,client,Content-Security-Policy,X-Content-Type-Options,X-XSS-Protection,Referer-Policy
    allowed-method: GET,POST,PUT,DELETE,OPTIONS
    allowed-origin:
      - 192.168.0.106:9000
      - 192.168.221.168:9000
  illegal-properties:
    enable: true
    order: -1
    exclude-url:
      - /demo/demo
  ignore-url:
    - /demo/demo
  static-url:
    - .ico
    - .js
    - .css
    - .html
    - .vue
